apiVersion: v1
kind: Service
metadata:
  name: validation-api-service
  namespace: neris-ai
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
spec:
  type: LoadBalancer
  selector:
    app: validation-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000