apiVersion: v1
kind: Service
metadata:
  name: validation-api-service
  namespace: neris-ai
spec:
  type: ClusterIP
  selector:
    app: validation-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000